version: 2

sources:
  - name: raw
    schema: gz_raw_data
    description: raw data source greenwizzzzz

    tables:
      - name: sales
        identifier: raw_gz_sales
        description: table des ventes
        freshness:
          warn_after: {count: 90, period: day}
        loaded_at_field: "CAST(date_date as TIMESTAMP)"
        columns:
          - name: concat(orders_id,"_",pdt_id)
            description: primary key of the table
            tests:
              - unique
              - not_null

      - name: product
        identifier: raw_gz_product
        description: table des produits
        columns:
          - name: products_id
            description: primary key of products table
            tests:
              - unique
              - not_null
                    
      - name: ship
        identifier: raw_gz_ship
        description: table des envoies
        columns:
          - name: orders_id
            description: primary key of ship table
            tests:
              - unique
              - not_null

      - name: google
        identifier: raw_gz_adwords
        description: table des ads google - clée primaire campaign key + date_date
        columns:
          - name: concat(date_date,"_",campaign_key)
            description: primary key of gads table table
            tests:
              - unique
              - not_null
      - name: bing
        identifier: raw_gz_bing
        description: table des ads bing - clée primaire campaign key
        columns:
          - name: concat(date_date,"_",campaign_key)
            description: primary key of bing ads table table
            tests:
              - unique
              - not_null
    
      - name: facebook
        identifier: raw_gz_facebook
        description: table des ads facebook - clée primaire campaign key + date_date
        columns:
          - name: concat(date_date,"_",campaign_key)
            description: primary key of bing ads table table
            tests:
              - unique
              - not_null
      - name: criteo
        identifier: raw_gz_criteo
        description: table des ads facebook - clée primaire campaign key + date_date
        columns:
          - name: concat(date_date,"_",campaign_key)
            description: primary key of bing ads table table
            tests:
              - unique
              - not_null
          - name: camPGN_name	
            tests:
              - not_null



    
    
        
